### PR TITLE
Tilde quoting

### PR DESCRIPTION
**Pull request by avaer**
This fixes selector cases like `[data-unity-loaded='true'] #loader` which crashed because of a double-`'` quoting issue.

### CODE REVIEW

**Comment by avaer** [comment]
Wrong upstream sorry!

**Comment by lauriro** [comment]
It is not a bad idea to push bugfixes to upstream.

It is a bad idea to replace someone's licence with your own and claim to be an author.

**Comment by avaer** [comment]
Sorry Lauri, are you meaning to object to a change in the fork?

As far as I can tell [license notice](https://github.com/modulesio/window-selector#licence) remains and GitHub labels the source of the fork.

**Comment by lauriro** [comment]
I noticed "Re-own package.json" commit with new author and "Create LICENSE.md" with "Copyright (c) 2018 Avaer Kazmer ..." content.

Basically the only condition of MIT license is to preserve attribution, beside that you can do what you like.

Looking closer, as your changes would not apply to my repo any more (due to syntax change),
my humble suggestion is to keep same copyright across a fork (not one in README and different in LICENSE) - you can add but not remove, and I would like to know when actual bug is found.

I do use this code on production and it has been stable.

**Pull request closed without merging**
